FROM openjdk:11.0

RUN cd /opt \
&& curl -LfO https://downloads.apache.org/kafka/2.8.0/kafka_2.13-2.8.0.tgz \
&& tar -xzvf kafka_2.13-2.8.0.tgz \
&& rm kafka_2.13-2.8.0.tgz \
&& cd kafka_2.13-2.8.0

#ENV KAFKA_HOME=/opt/kafka_2.13-2.8.0
#ENV PATH=${PATH}:${KAFKA_HOME}/bin

CMD ["/opt/kafka_2.13-2.8.0/bin/zookeeper-server-start.sh", "/opt/kafka_2.13-2.8.0/config/zookeeper.properties"]